import React from 'react'
import { ReactNavbar } from 'overlay-navbar';
import logo from '../../Images/ecommerceLogo.jpg'
import searchIcon from '../../Images/searchIcon.jpg'
import cartIcon from '../../Images/shoppingCart.png'
import avatar from '../../Images/userIcon.png'

const Header = () => {
    return (
        <ReactNavbar
            burgerColor="black"
            burgerColorHover="burgerColor"
            navColor1="rgb(179, 217, 250)"
            navColor2="rgb(179, 217, 250)"
            navColor3="rgb(179, 217, 250)"
            navColor4="rgb(179, 217, 250)"
            logo={logo}
            logoWidth="100px"
            logoHeight="100px"
            logoHoverSize="15px"
            logoHoverColor="green"
            logoTransition="0.5	"
            logoAnimationTime="1"
            nav1FlexDirection="row"
            nav2FlexDirection="row"
            nav3FlexDirection="row"
            nav4FlexDirection="row"
            nav1alignItems="center"
            nav2alignItems="center"
            nav3alignItems="center"
            nav4alignItems="center"
            nav1justifyContent="center"
            nav2justifyContent="center"
            nav3justifyContent="center"
            nav4justifyContent="center"
            nav1Transition="0.4"
            nav2Transition="0.8"
            nav3Transition="1.2"
            nav4Transition="1.6"
            link1Text="Home"
            link2Text="Products"
            link3Text="Cart"
            link4Text="Profile"
            link1Url="/"
            link2Url="/products"
            link3Url="/cart"
            link4Url="/profile"
            link1Size="2vmax"
            link2Size="2vmax"
            link3Size="2vmax"
            link4Size="2vmax"
            link1Family="Lucida Sans"
            link2Family="Lucida Sans"
            link3Family="Lucida Sans"
            link4Family="Lucida Sans"
            link1Color="black"
            link2Color="black "
            link3Color="black "
            link4Color="black "
            link1BackgroundColor="unset"
            link2BackgroundColor="unset"
            link3BackgroundColor="unset"
            link4BackgroundColor="unset"
            link1ColorHover="rgb(9, 97, 34)"
            link2ColorHover="rgb(9, 97, 34)"
            link3ColorHover="rgb(9, 97, 34)"
            link4ColorHover="rgb(9, 97, 34)"
            link1Decoration="none"
            link2Decoration="none"
            link3Decoration="none"
            link4Decoration="none"
            link1Margin="2vmax"
            link2Margin="2vmax "
            link3Margin="2vmax "
            link4Margin="2vmax "
            link1Padding="0"
            link2Padding="0"
            link3Padding="0"
            link4Padding="0 "
            link1Border="none"
            link2Border="none"
            link3Border="none"
            link4Border="none"
            link1Transition="0.5"
            link2Transition="0.5"
            link3Transition="0.5"
            link4Transition="0.5"
            link1AnimationTime="1.5"
            link2AnimationTime="2.0"
            link3AnimationTime="2.5"
            link4AnimationTime="3.0"
            // searchIcon	={true}
            SearchIconElement={searchIcon}
            // cartIcon	= "true"	
            CartIconElement={cartIcon}
            // profileIcon	="true"
            ProfileIconElement={avatar}
            searchIconMargin="0"
            cartIconMargin="0"
            profileIconMargin="0"
            searchIconUrl="/search"
            cartIconUrl="/cart"
            profileIconUrl="/account"
            searchIconSize="2vmax"
            cartIconSize="2vmax"
            profileIconSize="2.5vmax"
            searchIconColor="white"
            // cartIconSize	="white"	
            profileIconColor="white"
            searchIconColorHover="white"
            cartIconColorHover="white"
            profileIconColorHover="white"
            searchIconTransition="0.5"
            cartIconTransition="0.5"
            profileIconTransition="0.5"
            searchIconAnimationTime="2"
            cartIconAnimationTime="2.5"
            profileIconAnimationTime="3"
        > </ReactNavbar >
    )
}

export default Header